namespace CrowdFunding.Modules.Campaigns.Application.Features.RewardTiers.Commands.ReleaseExpiredRewardTierReservation;

public sealed record ReleaseExpiredRewardTierReservationResult(Guid ReservationId, bool Released);
